import type { Metadata } from "next";
import { Exo } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/navbar/page";
import Footer from "./_components/navbar/footer/page";
import { cn } from "@/lib/utils";
import FirstNav from "./_components/FirstNav/page";
import { Toaster } from "@/components/ui/toast"
import MyProvider from "./_components/MyProvider/MyProvider";




const ExoFont = Exo({
  variable: "--font-Exo",
 weight : ['200' , '400' , '700']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html  lang="en" className={`${ExoFont.className} antialiased`  }  >
     
      
   
      {/* <FirstNav/> */}
     
      <body className="min-h-full bg-gray-200  flex flex-col">
       
<MyProvider>
   <Navbar/>
        {children}
         <Toaster/>
      <Footer/>
</MyProvider>
 

        
     
        </body>
     
    </html>
  );
}
